version: '3.8'

services:
  db:
    image: postgres:15
    container_name: burmalda
    environment:
      POSTGRES_DB: bigdick
      POSTGRES_USER: postrgres
      POSTGRES_PASSWORD: postrgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  pgdata:
